[package]
name = "Search-Engine"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
sprs = "0.11"
actix-web = "4.3.1"
actix-cors = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", features = ["full"] }
ndarray = "0.16"
ndarray-linalg = "0.17"